name: ripeto_flutter
description: Habit formation app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.4
#  google_sign_in: ^5.2.1
  google_fonts: ^2.1.0
#  flutter_signin_button: ^2.0.0
#  provider: ^6.0.1
  shared_preferences: ^2.0.9
  modal_progress_hud: ^0.1.3
#  pull_to_refresh: ^2.0.0
#  day_picker: ^2.1.0
#  uuid: ^3.0.5
  weekday_selector: ^1.0.0
  persistent_bottom_nav_bar: ^4.0.2
  table_calendar: ^3.0.3
  firebase_messaging: ^11.2.5
  flutter_local_notifications: ^9.2.0
#  awesome_notifications: ^0.6.21
  timezone: ^0.8.0
  syncfusion_flutter_calendar: ^19.4.47


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


